feat: add index.d.ts
remarkjs/remark-slug pull request #17
Opened 2021-04-10 16:36 UTC by aleclarson

2021-04-10 18:33 UTC, ChristianMurphy requested changes
Thanks @aleclarson!
Could we add dtslint and a type test, similar to https://github.com/remarkjs/remark-breaks/pull/1 ?

2021-04-10 18:33 UTC, ChristianMurphy commented on index.d.ts
> +declare const remarkSlug: Plugin
the default generic on plugin accepts a single object like setting.
This plugin does not accept any settings, which can be specified with `<[]>`

```suggestion
declare const remarkSlug: Plugin<[]>
```

2021-04-10 18:36 UTC, aleclarson commented
> Could we add dtslint and a type test, similar to [remarkjs/remark-breaks#1](https://github.com/remarkjs/remark-breaks/pull/1) ?

Seems like overkill for what's basically a one liner?

2021-04-10 18:50 UTC, ChristianMurphy commented
There are 300+ repos across unified, syntax tree, remark, rehype, retext, and redot; with types being added to each over time.
Ensuring a basic level of quality for all the types is a goal.
Understanding what versions of TS are supported, and having a test in place for options or in case options are added, is valuable at an ecosystem level.

So to answer your question, no, it's isn't overkill.
The context is broader than a single repo with several line typing.

2021-04-10 19:01 UTC, aleclarson commented
If you're worried about that, maybe you could write a script I can run to set that up? Otherwise, these types work fine as of now. Someone else can contribute the test setup if they find it necessary.

2021-04-10 19:16 UTC, ChristianMurphy commented
> you could write a script I can run to set that up?

the setup is
```
npm install --save-dev dtslint
```

the tsconfig and tslint files shift from project to project, but you could use the ones from remarkjs/remark-breaks#1 as a starting point.
If you want to automate that more, feel free.

> Otherwise, these types work fine as of now

I'm sure it does for fine for you.
And with some test tooling in place, it can also match the community standards and be maintainable long term.

> Someone else can contribute the test setup if they find it necessary.

Or you could add it.
I'm personally not interested in merging an incomplete PR.
The PR is close, just a bit more and you can finish what you started.

2021-04-10 20:48 UTC, wooorm commented
New features should come with tests: https://github.com/remarkjs/.github/blob/main/contributing.md#submitting-a-pull-request.

Just a type file doesn't do anything, and this is failing existing tests. I don't think this is a weird or ambitious ask.

2021-04-10 21:16 UTC, aleclarson commented
Okay, should we keep this open until someone with the necessary willpower forks it and opens a follow-up PR? In the meantime, I've published [`@alloc/remark-slug`](https://www.npmjs.com/package/@alloc/remark-slug) with the types.

2021-04-11 08:35 UTC, remcohaszing commented
@unifiedjs / @remarkjs packages merely upholds the same quality standards for types as followed by [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). I know this is a very welcoming community willing to help first time contributors, especially @ChristianMurphy in my experience.

When contributing to an open source project, one should adhere to the quality standards of that project, even if they don’t like it. This doesn’t only apply to @unifiedjs, but to **any** open source contributions.

- Always read the contributing guidelines.
- Always adhere to the coding standards.
- Does a project have tests? Write tests for your contribution.
- Does a project certain conventions? Adhere to those conventions.
- Do you get feedback on your contribution? Process that feedback.

Not only is creating and maintaining a fork more work, also this contributes to fragmentation and unclarity within the JavaScript community. I hope you decide to deprecate `@alloc/remark-slug`. Otherwise, please fix your project metadata.

- Your default branch is behind, `master` is published instead.
- The project metadata should link to your fork, not to [remarkjs/remark-slug](https://github.com/remarkjs/remark-slug).
- The readme should state why the project was forked.

2021-04-11 18:05 UTC, wooorm commented
Going to close this! I am a bit flabbergasted by wanting to land a broken feature without tests, but if the author is not interested in working on this anymore, that's totally okay

2021-04-11 18:05 UTC, closed without merging

2021-04-23 18:25 UTC, aleclarson commented
> * Your default branch is behind, `master` is published instead.
> * The project metadata should link to your fork, not to [remarkjs/remark-slug](https://github.com/remarkjs/remark-slug).
> * The readme should state why the project was forked.

All fixed :)



> wanting to land a broken feature

It's working fine for me :)

2021-04-24 15:12 UTC, wooorm commented
> It's working fine for me :)

For one, types aren’t published, although I saw you’ve added that to your fork.

> All fixed :)

👍

2021-07-16 21:52 UTC, SalahAdDin commented
@aleclarson what happened with this?

2021-07-16 22:04 UTC, ChristianMurphy commented
@SalahAdDin you can see what happened in the thread above you comment :slightly_smiling_face: 
It remains unmerged because it doesn't include any type tests.

2021-07-27 16:01 UTC, ChristianMurphy commented
For folks coming across this thread in the future, @SalahAdDin was kind enough to open a follow up PR with types and type tests https://github.com/remarkjs/remark-slug/pull/19
The types are now included in version https://github.com/remarkjs/remark-slug/releases/tag/6.1.0 and above.